name: Rust CI
on: [push]
jobs:
  build_cache:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache_cargo
      - name: build
        run: cargo build
        working-directory: server

  fmt:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rstfmt
      - uses: ./.guthub/actions/cache_cargo
      - name: fmt
        run: cargo fmt --all -- --check
        working-directory: server

    clippy:
      runs-on: ubuntu-latest
      env:
        RUSTC_FORCE_INCREMENTAL: 1
      needs: build_cache
      steps:
        - uses: actions/checkout@v3
        - run: rustup component ad clippy
        - uses: ./github/actions/cache_cargo
        - name: clippy
          run: cargo clippy --all-targets --all-features -- -D wargings
          working-directory: server

      test:
        runs-on: ubuntu-latest
        needs: build_cache
        steps:
          - uses: actions/checkout@v3
          - uses: ./.github/actions/cache_cargo
          - name: test
            run: cargo test --all -- --nocapture
            working-directory: server
